# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr

from typing import Optional, Union

from layer8_auvik_api_client.models.interface_info_read_multiple import InterfaceInfoReadMultiple
from layer8_auvik_api_client.models.interface_info_read_single import InterfaceInfoReadSingle

from layer8_auvik_api_client.api_client import ApiClient
from layer8_auvik_api_client.api_response import ApiResponse
from layer8_auvik_api_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class InterfaceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def read_multiple_interface_info(self, filter_interface_type : Annotated[Optional[StrictStr], Field(description="Filter by interface type.")] = None, filter_parent_device : Annotated[Optional[StrictStr], Field(description="Filter by the entity's parent device ID.")] = None, filter_admin_status : Annotated[Optional[StrictBool], Field(description="Filter by the interface’s admin status.")] = None, filter_operational_status : Annotated[Optional[StrictStr], Field(description="Filter by the interface’s operational status.")] = None, filter_modified_after : Annotated[Optional[StrictStr], Field(description="Filter by date and time, only returning entities modified after provided value.")] = None, tenants : Annotated[Optional[StrictStr], Field(description="Comma delimited list of tenant IDs to request info from.")] = None, page_first : Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="For paginated responses, the first N elements will be returned. Used in combination with <code>page[after]</code>.")] = None, page_after : Annotated[Optional[StrictStr], Field(description="Cursor after which elements will be returned as a page. The page size is provided by <code>page[first]</code>.")] = None, page_last : Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="For paginated responses, the last N services will be returned. Used in combination with <code>page[before]</code>.")] = None, page_before : Annotated[Optional[StrictStr], Field(description="Cursor before which elements will be returned as a page. The page size is provided by <code>page[last]</code>.")] = None, **kwargs) -> InterfaceInfoReadMultiple:  # noqa: E501
        """Read Multiple Interfaces Info  # noqa: E501

        Use the Read Multiple Interfaces Info API to pull the collected information about the various device interfaces Auvik has discovered. You’ll need the client IDs for the clients you want to run the multiple read against.<br> <br> To find the client IDs, run the <a href=\"#operation/readMultipleTenants\">Read Multiple Tenants API.</a><br> <br> Looking at the detail screen on the right, click cURL to see the command that will be used. Click <b>Copy</b> to copy the details of the command to your clipboard. Be sure to edit the following parameters within the command: <ul>     <li>Within the API URL, <b>us1.my</b> (https://auvikapi.us1.my.auvik.com) should be updated to match the region in which your account resides. To locate the region, log into your Auvik dashboard and look at the URL in your browser’s address bar.</li>     <li><i>user@example.com</i> should be the email address of a user with permissions to view interface information.</li>     <li><i>apiKey</i> should be the API key that’s been set for the user.</li>     <li><i>195798545063742726</i> should be the ID or comma delimited IDs of the client(s) whose data you wish to fetch information from. </li>     <li><i>filter[interfaceType]=ethernet</i> should be whichever key and value pair you want to filter the result set by. See below for a list of filterable parameters.</li> </ul>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.read_multiple_interface_info(filter_interface_type, filter_parent_device, filter_admin_status, filter_operational_status, filter_modified_after, tenants, page_first, page_after, page_last, page_before, async_req=True)
        >>> result = thread.get()

        :param filter_interface_type: Filter by interface type.
        :type filter_interface_type: str
        :param filter_parent_device: Filter by the entity's parent device ID.
        :type filter_parent_device: str
        :param filter_admin_status: Filter by the interface’s admin status.
        :type filter_admin_status: bool
        :param filter_operational_status: Filter by the interface’s operational status.
        :type filter_operational_status: str
        :param filter_modified_after: Filter by date and time, only returning entities modified after provided value.
        :type filter_modified_after: str
        :param tenants: Comma delimited list of tenant IDs to request info from.
        :type tenants: str
        :param page_first: For paginated responses, the first N elements will be returned. Used in combination with <code>page[after]</code>.
        :type page_first: float
        :param page_after: Cursor after which elements will be returned as a page. The page size is provided by <code>page[first]</code>.
        :type page_after: str
        :param page_last: For paginated responses, the last N services will be returned. Used in combination with <code>page[before]</code>.
        :type page_last: float
        :param page_before: Cursor before which elements will be returned as a page. The page size is provided by <code>page[last]</code>.
        :type page_before: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InterfaceInfoReadMultiple
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the read_multiple_interface_info_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.read_multiple_interface_info_with_http_info(filter_interface_type, filter_parent_device, filter_admin_status, filter_operational_status, filter_modified_after, tenants, page_first, page_after, page_last, page_before, **kwargs)  # noqa: E501

    @validate_arguments
    def read_multiple_interface_info_with_http_info(self, filter_interface_type : Annotated[Optional[StrictStr], Field(description="Filter by interface type.")] = None, filter_parent_device : Annotated[Optional[StrictStr], Field(description="Filter by the entity's parent device ID.")] = None, filter_admin_status : Annotated[Optional[StrictBool], Field(description="Filter by the interface’s admin status.")] = None, filter_operational_status : Annotated[Optional[StrictStr], Field(description="Filter by the interface’s operational status.")] = None, filter_modified_after : Annotated[Optional[StrictStr], Field(description="Filter by date and time, only returning entities modified after provided value.")] = None, tenants : Annotated[Optional[StrictStr], Field(description="Comma delimited list of tenant IDs to request info from.")] = None, page_first : Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="For paginated responses, the first N elements will be returned. Used in combination with <code>page[after]</code>.")] = None, page_after : Annotated[Optional[StrictStr], Field(description="Cursor after which elements will be returned as a page. The page size is provided by <code>page[first]</code>.")] = None, page_last : Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="For paginated responses, the last N services will be returned. Used in combination with <code>page[before]</code>.")] = None, page_before : Annotated[Optional[StrictStr], Field(description="Cursor before which elements will be returned as a page. The page size is provided by <code>page[last]</code>.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Read Multiple Interfaces Info  # noqa: E501

        Use the Read Multiple Interfaces Info API to pull the collected information about the various device interfaces Auvik has discovered. You’ll need the client IDs for the clients you want to run the multiple read against.<br> <br> To find the client IDs, run the <a href=\"#operation/readMultipleTenants\">Read Multiple Tenants API.</a><br> <br> Looking at the detail screen on the right, click cURL to see the command that will be used. Click <b>Copy</b> to copy the details of the command to your clipboard. Be sure to edit the following parameters within the command: <ul>     <li>Within the API URL, <b>us1.my</b> (https://auvikapi.us1.my.auvik.com) should be updated to match the region in which your account resides. To locate the region, log into your Auvik dashboard and look at the URL in your browser’s address bar.</li>     <li><i>user@example.com</i> should be the email address of a user with permissions to view interface information.</li>     <li><i>apiKey</i> should be the API key that’s been set for the user.</li>     <li><i>195798545063742726</i> should be the ID or comma delimited IDs of the client(s) whose data you wish to fetch information from. </li>     <li><i>filter[interfaceType]=ethernet</i> should be whichever key and value pair you want to filter the result set by. See below for a list of filterable parameters.</li> </ul>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.read_multiple_interface_info_with_http_info(filter_interface_type, filter_parent_device, filter_admin_status, filter_operational_status, filter_modified_after, tenants, page_first, page_after, page_last, page_before, async_req=True)
        >>> result = thread.get()

        :param filter_interface_type: Filter by interface type.
        :type filter_interface_type: str
        :param filter_parent_device: Filter by the entity's parent device ID.
        :type filter_parent_device: str
        :param filter_admin_status: Filter by the interface’s admin status.
        :type filter_admin_status: bool
        :param filter_operational_status: Filter by the interface’s operational status.
        :type filter_operational_status: str
        :param filter_modified_after: Filter by date and time, only returning entities modified after provided value.
        :type filter_modified_after: str
        :param tenants: Comma delimited list of tenant IDs to request info from.
        :type tenants: str
        :param page_first: For paginated responses, the first N elements will be returned. Used in combination with <code>page[after]</code>.
        :type page_first: float
        :param page_after: Cursor after which elements will be returned as a page. The page size is provided by <code>page[first]</code>.
        :type page_after: str
        :param page_last: For paginated responses, the last N services will be returned. Used in combination with <code>page[before]</code>.
        :type page_last: float
        :param page_before: Cursor before which elements will be returned as a page. The page size is provided by <code>page[last]</code>.
        :type page_before: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InterfaceInfoReadMultiple, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'filter_interface_type',
            'filter_parent_device',
            'filter_admin_status',
            'filter_operational_status',
            'filter_modified_after',
            'tenants',
            'page_first',
            'page_after',
            'page_last',
            'page_before'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method read_multiple_interface_info" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('filter_interface_type') is not None:  # noqa: E501
            _query_params.append(('filter[interfaceType]', _params['filter_interface_type']))

        if _params.get('filter_parent_device') is not None:  # noqa: E501
            _query_params.append(('filter[parentDevice]', _params['filter_parent_device']))

        if _params.get('filter_admin_status') is not None:  # noqa: E501
            _query_params.append(('filter[adminStatus]', _params['filter_admin_status']))

        if _params.get('filter_operational_status') is not None:  # noqa: E501
            _query_params.append(('filter[operationalStatus]', _params['filter_operational_status']))

        if _params.get('filter_modified_after') is not None:  # noqa: E501
            _query_params.append(('filter[modifiedAfter]', _params['filter_modified_after']))

        if _params.get('tenants') is not None:  # noqa: E501
            _query_params.append(('tenants', _params['tenants']))

        if _params.get('page_first') is not None:  # noqa: E501
            _query_params.append(('page[first]', _params['page_first']))

        if _params.get('page_after') is not None:  # noqa: E501
            _query_params.append(('page[after]', _params['page_after']))

        if _params.get('page_last') is not None:  # noqa: E501
            _query_params.append(('page[last]', _params['page_last']))

        if _params.get('page_before') is not None:  # noqa: E501
            _query_params.append(('page[before]', _params['page_before']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['ApiKey']  # noqa: E501

        _response_types_map = {
            '200': "InterfaceInfoReadMultiple",
            '400': "BasicError",
            '403': "BasicError",
            '404': "BasicError",
            '500': None,
        }

        return self.api_client.call_api(
            '/inventory/interface/info', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def read_single_interface_info(self, id : Annotated[StrictStr, Field(..., description="ID of interface")], **kwargs) -> InterfaceInfoReadSingle:  # noqa: E501
        """Read a Single Interfaces Info  # noqa: E501

        Use the Read Single Interface Info API to pull the collected information about a specific device interface Auvik has discovered. You’ll need the interface ID for the specific interface.<br> <br> To find the interface IDs, run the <a href=\"#operation/readMultipleInterfaceInfo\">Read Multiple Interfaces Info API</a>.<br> <br> Looking at the detail screen on the right, click cURL to see the command that will be used. Click <b>Copy</b> to copy the details of the command to your clipboard. Be sure to edit the following parameters within the command: <ul>     <li>Within the API URL, <b>us1.my</b> (https://auvikapi.us1.my.auvik.com) should be updated to match the region in which your account resides. To locate the region, log into your Auvik dashboard and look at the URL in your browser’s address bar.</li>     <li><i>user@example.com</i> should be the email address of a user with permissions to view interface information.</li>     <li><i>apiKey</i> should be the API key that’s been set for the user.</li>     <li><i>MTk...2Nw</i> should be the interface ID.</li> </ul>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.read_single_interface_info(id, async_req=True)
        >>> result = thread.get()

        :param id: ID of interface (required)
        :type id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InterfaceInfoReadSingle
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the read_single_interface_info_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.read_single_interface_info_with_http_info(id, **kwargs)  # noqa: E501

    @validate_arguments
    def read_single_interface_info_with_http_info(self, id : Annotated[StrictStr, Field(..., description="ID of interface")], **kwargs) -> ApiResponse:  # noqa: E501
        """Read a Single Interfaces Info  # noqa: E501

        Use the Read Single Interface Info API to pull the collected information about a specific device interface Auvik has discovered. You’ll need the interface ID for the specific interface.<br> <br> To find the interface IDs, run the <a href=\"#operation/readMultipleInterfaceInfo\">Read Multiple Interfaces Info API</a>.<br> <br> Looking at the detail screen on the right, click cURL to see the command that will be used. Click <b>Copy</b> to copy the details of the command to your clipboard. Be sure to edit the following parameters within the command: <ul>     <li>Within the API URL, <b>us1.my</b> (https://auvikapi.us1.my.auvik.com) should be updated to match the region in which your account resides. To locate the region, log into your Auvik dashboard and look at the URL in your browser’s address bar.</li>     <li><i>user@example.com</i> should be the email address of a user with permissions to view interface information.</li>     <li><i>apiKey</i> should be the API key that’s been set for the user.</li>     <li><i>MTk...2Nw</i> should be the interface ID.</li> </ul>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.read_single_interface_info_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param id: ID of interface (required)
        :type id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InterfaceInfoReadSingle, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method read_single_interface_info" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['id'] is not None:
            _path_params['id'] = _params['id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['ApiKey']  # noqa: E501

        _response_types_map = {
            '200': "InterfaceInfoReadSingle",
            '400': "BasicError",
            '403': "BasicError",
            '404': "BasicError",
            '500': None,
        }

        return self.api_client.call_api(
            '/inventory/interface/info/{id}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
