# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from layer8_auvik_api_client.models.controller_all_of_attributes import ControllerAllOfAttributes  # noqa: E501

class TestControllerAllOfAttributes(unittest.TestCase):
    """ControllerAllOfAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ControllerAllOfAttributes:
        """Test ControllerAllOfAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ControllerAllOfAttributes`
        """
        model = ControllerAllOfAttributes()  # noqa: E501
        if include_optional:
            return ControllerAllOfAttributes(
                device_name = 'SomeDevice',
                last_modified = '2018-03-12T12:00:00.000Z',
                last_seen_time = '2018-11-30T18:34:39.452Z',
                device_type = 'controller'
            )
        else:
            return ControllerAllOfAttributes(
                device_name = 'SomeDevice',
                device_type = 'controller',
        )
        """

    def testControllerAllOfAttributes(self):
        """Test ControllerAllOfAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
