# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from layer8_auvik_api_client.models.snmp_poller_setting_devices_read import SnmpPollerSettingDevicesRead  # noqa: E501

class TestSnmpPollerSettingDevicesRead(unittest.TestCase):
    """SnmpPollerSettingDevicesRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnmpPollerSettingDevicesRead:
        """Test SnmpPollerSettingDevicesRead
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnmpPollerSettingDevicesRead`
        """
        model = SnmpPollerSettingDevicesRead()  # noqa: E501
        if include_optional:
            return SnmpPollerSettingDevicesRead(
                data = [
                    layer8_auvik_api_client.models.snmp_poller_setting_device_resource_object.snmpPollerSettingDeviceResourceObject(
                        id = 'MTk5NTAyNzg2ODc3MDYzNDI1LDE5OTUwMjc5MTExMzAyODg2Nw', 
                        type = 'snmpPollerSettingDevice', 
                        attributes = layer8_auvik_api_client.models.snmp_poller_setting_device_attributes.snmpPollerSettingDeviceAttributes(
                            name = 'Cisco Router', 
                            type = 'accessPoint', ), 
                        relationships = layer8_auvik_api_client.models.snmp_poller_setting_device_relationships.snmpPollerSettingDeviceRelationships(
                            tenant = layer8_auvik_api_client.models.tenant.tenant(
                                data = layer8_auvik_api_client.models.tenant_data.tenant_data(
                                    type = 'tenant', 
                                    id = '195798545063742726', ), ), 
                            snmp_poller_setting = layer8_auvik_api_client.models.snmp_poller_setting.snmpPollerSetting(), ), 
                        links = layer8_auvik_api_client.models.snmp_poller_setting_device_resource_object_links.snmpPollerSettingDeviceResourceObject_links(
                            dashboard = 'http://office.local.auvik.com:9000/#entity/device/7798604142709656/dashboard', 
                            self = 'https://auvikapi.us1.my.auvik.com/v1/inventory/device/info/NzkyMyw3Nzk4NjA0MTQyNzA5NjU2MzE=', ), )
                    ],
                links = layer8_auvik_api_client.models.snmp_poller_setting_devices_read_links.snmpPollerSettingDevicesRead_links(
                    next = 'https://auvikapi.us1.my.auvik.com/v1/settings/snmppoller/MTk5NTAyNzg2ODc3MDYzNDI1LDE5OTUwMjc5MTExMzAyODg2Nw/devices?page[after]=Y3Vyc29yOk16TXpPVE0wT0RRNU1UQTROemN4TlRneExETXpNemt6TkRnME56QXpORFF5TmpFeU5R&page[first]=300', 
                    prev = 'https://auvikapi.us1.my.auvik.com/v1/settings/snmppoller/MTk5NTAyNzg2ODc3MDYzNDI1LDE5OTUwMjc5MTExMzAyODg2Nw/devices?page[before]=Y3Vyc29yOk16TXpPVE0wT0RRNU1UQTROemN4TlRneExETXpNemt6TkRnME56QXpORFF5TmpFeU5R&page[last]=300', 
                    first = 'https://auvikapi.us1.my.auvik.com/v1/settings/snmppoller/MTk5NTAyNzg2ODc3MDYzNDI1LDE5OTUwMjc5MTExMzAyODg2Nw/devices?page[first]=300', 
                    last = 'https://auvikapi.us1.my.auvik.com/v1/settings/snmppoller/MTk5NTAyNzg2ODc3MDYzNDI1LDE5OTUwMjc5MTExMzAyODg2Nw/devices?page[last]=300', )
            )
        else:
            return SnmpPollerSettingDevicesRead(
        )
        """

    def testSnmpPollerSettingDevicesRead(self):
        """Test SnmpPollerSettingDevicesRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
