# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from layer8_auvik_api_client.models.device_attributes import DeviceAttributes  # noqa: E501

class TestDeviceAttributes(unittest.TestCase):
    """DeviceAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceAttributes:
        """Test DeviceAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceAttributes`
        """
        model = DeviceAttributes()  # noqa: E501
        if include_optional:
            return DeviceAttributes(
                ip_addresses = ["10.0.0.1"],
                device_name = 'MyAccessPoint',
                device_type = 'accessPoint',
                make_model = 'M Series Access Point',
                vendor_name = 'Ubiquiti',
                software_version = '3.9.3.7537',
                serial_number = '1Q2W3E4R5T6Y',
                description = 'Linux 3.3.8 #1 Fri Oct 13 11:12:44 PDT 2017 mips',
                firmware_version = 'unifi-v1.6.7.249-gb74e0282',
                last_modified = '2018-03-12T12:00:00.000Z',
                last_seen_time = '2018-11-30T18:34:39.452Z',
                online_status = 'online'
            )
        else:
            return DeviceAttributes(
                ip_addresses = ["10.0.0.1"],
                device_name = 'MyAccessPoint',
                device_type = 'accessPoint',
                make_model = 'M Series Access Point',
                vendor_name = 'Ubiquiti',
                software_version = '3.9.3.7537',
                serial_number = '1Q2W3E4R5T6Y',
                description = 'Linux 3.3.8 #1 Fri Oct 13 11:12:44 PDT 2017 mips',
                firmware_version = 'unifi-v1.6.7.249-gb74e0282',
                last_modified = '2018-03-12T12:00:00.000Z',
                online_status = 'online',
        )
        """

    def testDeviceAttributes(self):
        """Test DeviceAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
