# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from layer8_auvik_api_client.models.component_info_read_multiple import ComponentInfoReadMultiple  # noqa: E501

class TestComponentInfoReadMultiple(unittest.TestCase):
    """ComponentInfoReadMultiple unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComponentInfoReadMultiple:
        """Test ComponentInfoReadMultiple
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComponentInfoReadMultiple`
        """
        model = ComponentInfoReadMultiple()  # noqa: E501
        if include_optional:
            return ComponentInfoReadMultiple(
                data = [
                    layer8_auvik_api_client.models.components_resource_object.componentsResourceObject(
                        type = 'component', 
                        id = 'MTg2OTI2NTY1MDQ3MDExMDc0LDE5Nzc2OTU1ODM1MTAyMTMxOA', 
                        attributes = layer8_auvik_api_client.models.component_attributes.componentAttributes(
                            component_name = 'CPU Core 26', 
                            component_type = 'cpu', 
                            current_status = 'ok', 
                            last_modified = '2018-03-13T12:00:00.000Z', ), 
                        links = layer8_auvik_api_client.models.components_resource_object_links.componentsResourceObject_links(
                            dashboard = 'https://sampledomain.my.auvik.com/#entity/device/197769558351021318/cpu', 
                            self = 'https://auvikapi.us1.my.auvik.com/v1/inventory/component/info/MTk5NTAyNzg2ODc3MDYzMTY5LDE5OTUwMjc5MTExMjc4NTkyMw', ), 
                        relationships = layer8_auvik_api_client.models.component_relationships.componentRelationships(
                            tenant = layer8_auvik_api_client.models.tenant.tenant(
                                data = layer8_auvik_api_client.models.tenant_data.tenant_data(
                                    type = 'tenant', 
                                    id = '195798545063742726', ), ), 
                            parent_device = layer8_auvik_api_client.models.component_relationships_parent_device.componentRelationships_parentDevice(), ), )
                    ],
                links = layer8_auvik_api_client.models.component_info_read_multiple_links.componentInfoReadMultiple_links(
                    next = 'https://auvikapi.us1.my.auvik.com/v1/inventory/component/info?page[after]=Y3Vyc29yOk16TXpPVE0wT0RRNU1UQTROemN4TlRneExETXpNemt6TkRnME56QXpORFF5TmpFeU5R&page[first]=300', 
                    prev = 'https://auvikapi.us1.my.auvik.com/v1/inventory/component/info?page[before]=Y3Vyc29yOk16TXpPVE0wT0RRNU1UQTROemN4TlRneExETXpNemt6TkRnME56QXpORFF5TmpFeU5R&page[last]=300', 
                    first = 'https://auvikapi.us1.my.auvik.com/v1/inventory/component/info?page[first]=300', 
                    last = 'https://auvikapi.us1.my.auvik.com/v1/inventory/component/info?page[last]=300', ),
                meta = layer8_auvik_api_client.models.meta_object.meta object(
                    total_pages = 5, )
            )
        else:
            return ComponentInfoReadMultiple(
        )
        """

    def testComponentInfoReadMultiple(self):
        """Test ComponentInfoReadMultiple"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
