# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from layer8_auvik_api_client.models.device_warranty_attributes import DeviceWarrantyAttributes  # noqa: E501

class TestDeviceWarrantyAttributes(unittest.TestCase):
    """DeviceWarrantyAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceWarrantyAttributes:
        """Test DeviceWarrantyAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceWarrantyAttributes`
        """
        model = DeviceWarrantyAttributes()  # noqa: E501
        if include_optional:
            return DeviceWarrantyAttributes(
                device_name = 'MyAccessPoint',
                service_coverage_status = 'Covered',
                service_attachment_status = 'Available',
                contract_renewal_availability = 'Available',
                warranty_coverage_status = 'Not Covered',
                warranty_expiration_date = '2015-07-31T00:00:00.000Z',
                recommended_software_version = '15.1(4)M12a - 06 Oct 2016'
            )
        else:
            return DeviceWarrantyAttributes(
                device_name = 'MyAccessPoint',
                service_coverage_status = 'Covered',
                warranty_coverage_status = 'Not Covered',
                warranty_expiration_date = '2015-07-31T00:00:00.000Z',
                recommended_software_version = '15.1(4)M12a - 06 Oct 2016',
        )
        """

    def testDeviceWarrantyAttributes(self):
        """Test DeviceWarrantyAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
