# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from layer8_auvik_api_client.models.misc_device_all_of_attributes import MiscDeviceAllOfAttributes  # noqa: E501

class TestMiscDeviceAllOfAttributes(unittest.TestCase):
    """MiscDeviceAllOfAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MiscDeviceAllOfAttributes:
        """Test MiscDeviceAllOfAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MiscDeviceAllOfAttributes`
        """
        model = MiscDeviceAllOfAttributes()  # noqa: E501
        if include_optional:
            return MiscDeviceAllOfAttributes(
                device_name = 'SomeDevice',
                last_modified = '2018-03-12T12:00:00.000Z',
                last_seen_time = '2018-11-30T18:34:39.452Z',
                device_type = 'switch',
                tunnels = [
                    layer8_auvik_api_client.models.misc_device_all_of_attributes_all_of_tunnels_inner.miscDevice_allOf_attributes_allOf_tunnels_inner(
                        name_phase1 = 'Phase One', 
                        name_phase2 = 'Phase Two', 
                        local_gateway = '10.0.0.0', 
                        remote_gateway = '192.168.0.1', 
                        source_begin_ip = '255.255.255.0', 
                        source_end_ip = '255.255.255.255', 
                        destination_begin_ip = '255.255.255.0', 
                        destination_end_ip = '255.255.255.255', )
                    ]
            )
        else:
            return MiscDeviceAllOfAttributes(
                device_name = 'SomeDevice',
                device_type = 'switch',
                tunnels = [
                    layer8_auvik_api_client.models.misc_device_all_of_attributes_all_of_tunnels_inner.miscDevice_allOf_attributes_allOf_tunnels_inner(
                        name_phase1 = 'Phase One', 
                        name_phase2 = 'Phase Two', 
                        local_gateway = '10.0.0.0', 
                        remote_gateway = '192.168.0.1', 
                        source_begin_ip = '255.255.255.0', 
                        source_end_ip = '255.255.255.255', 
                        destination_begin_ip = '255.255.255.0', 
                        destination_end_ip = '255.255.255.255', )
                    ],
        )
        """

    def testMiscDeviceAllOfAttributes(self):
        """Test MiscDeviceAllOfAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
