# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from layer8_auvik_api_client.models.device_details_relationships_components import DeviceDetailsRelationshipsComponents
from layer8_auvik_api_client.models.device_details_relationships_configurations import DeviceDetailsRelationshipsConfigurations
from layer8_auvik_api_client.models.device_details_relationships_connected_devices import DeviceDetailsRelationshipsConnectedDevices
from layer8_auvik_api_client.models.device_details_relationships_interfaces import DeviceDetailsRelationshipsInterfaces
from layer8_auvik_api_client.models.tenant import Tenant

class DeviceDetailsRelationships(BaseModel):
    """
    This device's relationships to other resources  # noqa: E501
    """
    tenant: Optional[Tenant] = None
    connected_devices: Optional[DeviceDetailsRelationshipsConnectedDevices] = Field(None, alias="connectedDevices")
    interfaces: Optional[DeviceDetailsRelationshipsInterfaces] = None
    configurations: Optional[DeviceDetailsRelationshipsConfigurations] = None
    components: Optional[DeviceDetailsRelationshipsComponents] = None
    __properties = ["tenant", "connectedDevices", "interfaces", "configurations", "components"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DeviceDetailsRelationships:
        """Create an instance of DeviceDetailsRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of tenant
        if self.tenant:
            _dict['tenant'] = self.tenant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of connected_devices
        if self.connected_devices:
            _dict['connectedDevices'] = self.connected_devices.to_dict()
        # override the default output from pydantic by calling `to_dict()` of interfaces
        if self.interfaces:
            _dict['interfaces'] = self.interfaces.to_dict()
        # override the default output from pydantic by calling `to_dict()` of configurations
        if self.configurations:
            _dict['configurations'] = self.configurations.to_dict()
        # override the default output from pydantic by calling `to_dict()` of components
        if self.components:
            _dict['components'] = self.components.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DeviceDetailsRelationships:
        """Create an instance of DeviceDetailsRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DeviceDetailsRelationships.parse_obj(obj)

        _obj = DeviceDetailsRelationships.parse_obj({
            "tenant": Tenant.from_dict(obj.get("tenant")) if obj.get("tenant") is not None else None,
            "connected_devices": DeviceDetailsRelationshipsConnectedDevices.from_dict(obj.get("connectedDevices")) if obj.get("connectedDevices") is not None else None,
            "interfaces": DeviceDetailsRelationshipsInterfaces.from_dict(obj.get("interfaces")) if obj.get("interfaces") is not None else None,
            "configurations": DeviceDetailsRelationshipsConfigurations.from_dict(obj.get("configurations")) if obj.get("configurations") is not None else None,
            "components": DeviceDetailsRelationshipsComponents.from_dict(obj.get("components")) if obj.get("components") is not None else None
        })
        return _obj


