# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator
from layer8_auvik_api_client.models.device_attributes import DeviceAttributes
from layer8_auvik_api_client.models.device_relationships import DeviceRelationships
from layer8_auvik_api_client.models.devices_resource_object_links import DevicesResourceObjectLinks

class DevicesResourceObject(BaseModel):
    """
    The template for a resource object representing an Auvik device  # noqa: E501
    """
    type: Optional[StrictStr] = Field(None, description="The type of object in the API")
    id: Optional[StrictStr] = Field(None, description="The unique identifier for a device")
    attributes: Optional[DeviceAttributes] = None
    relationships: Optional[DeviceRelationships] = None
    links: Optional[DevicesResourceObjectLinks] = None
    __properties = ["type", "id", "attributes", "relationships", "links"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('device'):
            raise ValueError("must be one of enum values ('device')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DevicesResourceObject:
        """Create an instance of DevicesResourceObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of attributes
        if self.attributes:
            _dict['attributes'] = self.attributes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of relationships
        if self.relationships:
            _dict['relationships'] = self.relationships.to_dict()
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DevicesResourceObject:
        """Create an instance of DevicesResourceObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DevicesResourceObject.parse_obj(obj)

        _obj = DevicesResourceObject.parse_obj({
            "type": obj.get("type"),
            "id": obj.get("id"),
            "attributes": DeviceAttributes.from_dict(obj.get("attributes")) if obj.get("attributes") is not None else None,
            "relationships": DeviceRelationships.from_dict(obj.get("relationships")) if obj.get("relationships") is not None else None,
            "links": DevicesResourceObjectLinks.from_dict(obj.get("links")) if obj.get("links") is not None else None
        })
        return _obj


