# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from layer8_auvik_api_client.models.meta import Meta
from layer8_auvik_api_client.models.network_details_read_multiple_links import NetworkDetailsReadMultipleLinks
from layer8_auvik_api_client.models.network_details_resource_object import NetworkDetailsResourceObject

class NetworkDetailsReadMultiple(BaseModel):
    """
    Root level object per the json-api spec  # noqa: E501
    """
    data: Optional[conlist(NetworkDetailsResourceObject)] = None
    links: Optional[NetworkDetailsReadMultipleLinks] = None
    meta: Optional[Meta] = None
    __properties = ["data", "links", "meta"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NetworkDetailsReadMultiple:
        """Create an instance of NetworkDetailsReadMultiple from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item in self.data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['data'] = _items
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NetworkDetailsReadMultiple:
        """Create an instance of NetworkDetailsReadMultiple from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NetworkDetailsReadMultiple.parse_obj(obj)

        _obj = NetworkDetailsReadMultiple.parse_obj({
            "data": [NetworkDetailsResourceObject.from_dict(_item) for _item in obj.get("data")] if obj.get("data") is not None else None,
            "links": NetworkDetailsReadMultipleLinks.from_dict(obj.get("links")) if obj.get("links") is not None else None,
            "meta": Meta.from_dict(obj.get("meta")) if obj.get("meta") is not None else None
        })
        return _obj


