# coding: utf-8

"""
    Auvik API

    To use the Auvik APIs, you’ll need a <a href=\"https://support.auvik.com/hc/en-us/articles/204309114-#topic_generate\" target=\"_blank\">valid Auvik user and the user’s API key</a>. The user must also have the correct <a href=\" https://support.auvik.com/hc/en-us/articles/115002815966\" target=\"_blank\">role permissions</a>.<br>     <br>     Note: The word <i>tenant</i> as it appears in the API descriptions means one of Auvik’s supported tenant types: multi-client or client.<br><br>All date formats are formatted in the format of YYYY-MM-DDTHH:MM:SS.sssZ, as describe in ISO 8061<br><br>To find out more about Auvik’s APIs, <a href=\"https://support.auvik.com/hc/en-us/articles/360017965092\" target=\"_blank\">click here.</a>

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, validator

class NoteAttributes(BaseModel):
    """
    The type-specific properties of the notes object returned  # noqa: E501
    """
    title: StrictStr = Field(..., description="This note's title")
    body: StrictStr = Field(..., description="Content of this note")
    entity_id: StrictStr = Field(..., alias="entityId", description="The related entity's ID")
    entity_type: StrictStr = Field(..., alias="entityType", description="The related entity type")
    entity_name: StrictStr = Field(..., alias="entityName", description="The related entity's name")
    last_modified_by: StrictStr = Field(..., alias="lastModifiedBy", description="The username that last modified the note")
    last_modified: StrictStr = Field(..., alias="lastModified", description="When one of this entity note's attributes was last modified")
    __properties = ["title", "body", "entityId", "entityType", "entityName", "lastModifiedBy", "lastModified"]

    @validator('entity_type')
    def entity_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('root', 'device', 'network', 'interface'):
            raise ValueError("must be one of enum values ('root', 'device', 'network', 'interface')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NoteAttributes:
        """Create an instance of NoteAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NoteAttributes:
        """Create an instance of NoteAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NoteAttributes.parse_obj(obj)

        _obj = NoteAttributes.parse_obj({
            "title": obj.get("title"),
            "body": obj.get("body"),
            "entity_id": obj.get("entityId"),
            "entity_type": obj.get("entityType"),
            "entity_name": obj.get("entityName"),
            "last_modified_by": obj.get("lastModifiedBy"),
            "last_modified": obj.get("lastModified")
        })
        return _obj


